apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: campus-kafka-cluster
  namespace: kafka
  annotations:
    strimzi.io/use-kafka-node-pools: "true"
spec:
  kafka:
    version: 4.0.0
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9094 # Internal port the broker listens on
        type: nodeport # Use NodePort for simple local access
        tls: false
        configuration:
          brokers:
            - broker: 0
              advertisedHost: localhost
              advertisedPort: 9094
    config: 
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "4.0" 
  entityOperator:
    topicOperator: {}
    userOperator: {}
    #   - name: external
    #     port: 9094
    #     type: nodeport
    #     tls: false
    #     configuration:        
    #       brokers:
    #         - broker: 0
    #           advertisedHost: localhost
    #           advertisedPort: 31769
    #  config:
    #   offsets.topic.replication.factor: 1
    #   transaction.state.log.replication.factor: 1
    #   transaction.state.log.min.isr: 1
    #   default.replication.factor: 1
    #   min.insync.replicas: 1
    #   inter.broker.protocol.version: "4.0" 
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: controller
  namespace: kafka
  labels:
    strimzi.io/cluster: campus-kafka-cluster
spec:
  replicas: 1
  roles:
    - controller
  storage:
    type: ephemeral
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: broker
  namespace: kafka
  labels:
    strimzi.io/cluster: campus-kafka-cluster
spec:
  replicas: 1
  roles:
    - broker
  storage:
    type: ephemeral